# data.py — Dataset KosFind Semarang (Lengkap - 30 Kos)

KOS_DATA = [
    # ==================== KECAMATAN TEMBALANG (10 Kos) ====================
    {
        "id": 1,
        "nama": "Kos Mawar Putri",
        "alamat": "Jl. Tirto Agung No. 12, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 800000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "lemari", "kasur", "parkir motor", "air panas"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 22.00. Tamu perempuan diperbolehkan di ruang tamu. Tamu menginap perlu konfirmasi pemilik.",
        "rating": 4.5,
        "ulasan": 18,
        "whatsapp": "6281234567890",
        "latitude": -7.0478,
        "longitude": 110.4374,
        "dekat": ["kampus", "undip"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Kawasan aman banjir, drainase baik. Tidak pernah banjir.",
            "keamanan": "🔒 Ada CCTV di area parkir dan gerbang. Satpam jaga malam.",
            "kebersihan": "🧹 Dibersihkan setiap hari oleh petugas kebersihan.",
            "kebisingan": "🔇 Lokasi di gang kecil, cukup tenang.",
            "akses_jalan": "🚗 Jalan aspal mulus, bisa dilalui motor dan mobil.",
            "listrik": "⚡ Listrik 1300 watt, tidak pernah padam.",
            "air": "💧 Air sumur bor jernih, tersedia 24 jam.",
            "sirkulasi_udara": "🌬️ Kamar memiliki jendela besar, sirkulasi baik.",
            "pencahayaan": "💡 Penerangan jalan cukup terang.",
            "lingkungan": "🌳 Lingkungan asri, banyak pohon."
        }
    },
    {
        "id": 2,
        "nama": "Kos Melati Tembalang",
        "alamat": "Jl. Ngesrep Timur V No. 8, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 750000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "ac", "kasur", "meja"],
        "kamar_kosong": 0,
        "aturan": "Jam malam pukul 21.30. Tidak boleh membawa tamu lawan jenis.",
        "rating": 4.3,
        "ulasan": 12,
        "whatsapp": "6281234567891",
        "latitude": -7.0512,
        "longitude": 110.4385,
        "dekat": ["kampus", "undip"],
        "kondisi": {
            "rawan_banjir": True,
            "keterangan_banjir": "⚠️ PERHATIAN: Kawasan ini sering banjir saat hujan deras.",
            "keamanan": "🔒 Ada satpam hanya malam hari. Belum ada CCTV.",
            "kebersihan": "🧹 Dibersihkan setiap 2 hari sekali.",
            "kebisingan": "🔊 Lokasi dekat jalan raya, agak bising.",
            "akses_jalan": "🚗 Jalan aspal, tapi kadang becek saat hujan.",
            "listrik": "⚡ Listrik 900 watt, kadang padam.",
            "air": "💧 Air PAM, kadang keruh saat musim hujan.",
            "sirkulasi_udara": "🌬️ Kamar cukup pengap.",
            "pencahayaan": "💡 Lampu jalan redup.",
            "lingkungan": "🏘️ Lingkungan padat penduduk."
        }
    },
    {
        "id": 3,
        "nama": "Kos Kenanga",
        "alamat": "Jl. Banjarsari No. 5, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 600000,
        "jenis": "campur",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor", "dapur", "kipas"],
        "kamar_kosong": 3,
        "aturan": "Jam malam pukul 22.00. Tamu diperbolehkan sampai pukul 21.00.",
        "rating": 4.0,
        "ulasan": 9,
        "whatsapp": "6281234567892",
        "latitude": -7.0490,
        "longitude": 110.4360,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Area aman banjir.",
            "keamanan": "🔒 Tidak ada CCTV, tapi tetangga cukup peduli.",
            "kebersihan": "🧹 Kamar dibersihkan sendiri.",
            "kebisingan": "🔇 Tenang, di gang kecil.",
            "akses_jalan": "🚗 Jalan aspal, mobil bisa masuk.",
            "listrik": "⚡ Listrik 1300 watt, stabil.",
            "air": "💧 Air sumur, cukup jernih.",
            "sirkulasi_udara": "🌬️ Kamar ada jendela.",
            "pencahayaan": "💡 Penerangan cukup.",
            "lingkungan": "🌳 Lingkungan asri."
        }
    },
    {
        "id": 4,
        "nama": "Kos Flamboyan",
        "alamat": "Jl. Kampus Undip No. 15, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 900000,
        "jenis": "putri",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "kasur", "lemari", "parkir motor", "laundry"],
        "kamar_kosong": 1,
        "aturan": "Jam malam pukul 23.00. Tamu hanya sampai jam 21.00.",
        "rating": 4.7,
        "ulasan": 25,
        "whatsapp": "6281234567801",
        "latitude": -7.0500,
        "longitude": 110.4400,
        "dekat": ["kampus", "undip"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Bebas banjir, area perbukitan.",
            "keamanan": "🔒 Satpam 24 jam, CCTV di setiap sudut.",
            "kebersihan": "🧹 Sangat bersih, petugas 2 shift.",
            "kebisingan": "🔇 Tenang karena jauh dari jalan raya.",
            "akses_jalan": "🚗 Jalan lebar, aspal mulus.",
            "listrik": "⚡ Listrik 2200 watt, stabil.",
            "air": "💧 Air PDAM, jernih.",
            "sirkulasi_udara": "🌬️ Kamar luas dengan jendela besar.",
            "pencahayaan": "💡 Penerangan sangat baik.",
            "lingkungan": "🌳 Lingkungan kampus yang asri."
        }
    },
    {
        "id": 5,
        "nama": "Kos Cemara",
        "alamat": "Jl. Raya Tembalang No. 45, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 500000,
        "jenis": "putra",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor", "dapur"],
        "kamar_kosong": 5,
        "aturan": "Tidak ada jam malam. Bayar tepat waktu.",
        "rating": 3.8,
        "ulasan": 6,
        "whatsapp": "6281234567802",
        "latitude": -7.0480,
        "longitude": 110.4350,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Keamanan biasa, lingkungan cukup aman.",
            "kebersihan": "🧹 Cukup bersih.",
            "kebisingan": "🔊 Agak bising karena di pinggir jalan.",
            "akses_jalan": "🚗 Jalan raya, akses mudah.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air sumur.",
            "sirkulasi_udara": "🌬️ Kamar cukup nyaman.",
            "pencahayaan": "💡 Penerangan cukup.",
            "lingkungan": "🏘️ Lingkungan ramai."
        }
    },
    {
        "id": 6,
        "nama": "Kos Dahlia",
        "alamat": "Jl. Kutilang No. 8, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 650000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor", "kasur", "lemari"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.1,
        "ulasan": 10,
        "whatsapp": "6281234567803",
        "latitude": -7.0520,
        "longitude": 110.4390,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Ada pagar dan kunci gerbang.",
            "kebersihan": "🧹 Dibersihkan setiap hari.",
            "kebisingan": "🔇 Cukup tenang.",
            "akses_jalan": "🚗 Jalan aspal, cukup lebar.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Kamar ada jendela.",
            "pencahayaan": "💡 Penerangan cukup.",
            "lingkungan": "🏘️ Lingkungan perumahan."
        }
    },
    {
        "id": 7,
        "nama": "Kos Anggrek Tembalang",
        "alamat": "Jl. Gondang Timur No. 3, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 700000,
        "jenis": "campur",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "parkir motor", "dapur"],
        "kamar_kosong": 1,
        "aturan": "Jam malam pukul 22.00. Tamu diperbolehkan.",
        "rating": 4.2,
        "ulasan": 14,
        "whatsapp": "6281234567804",
        "latitude": -7.0530,
        "longitude": 110.4410,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Bebas banjir.",
            "keamanan": "🔒 CCTV di area parkir.",
            "kebersihan": "🧹 Bersih dan rapi.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan baik, bisa mobil.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Kamar ber-AC.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🏘️ Lingkungan nyaman."
        }
    },
    {
        "id": 8,
        "nama": "Kos Teratai Tembalang",
        "alamat": "Jl. Sanan No. 21, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 550000,
        "jenis": "putra",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor"],
        "kamar_kosong": 4,
        "aturan": "Tidak ada jam malam.",
        "rating": 3.9,
        "ulasan": 8,
        "whatsapp": "6281234567805",
        "latitude": -7.0460,
        "longitude": 110.4360,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Keamanan standar.",
            "kebersihan": "🧹 Cukup bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan gang agak sempit.",
            "listrik": "⚡ Listrik 900 watt.",
            "air": "💧 Air sumur.",
            "sirkulasi_udara": "🌬️ Kamar biasa.",
            "pencahayaan": "💡 Cukup.",
            "lingkungan": "🏘️ Lingkungan padat."
        }
    },
    {
        "id": 9,
        "nama": "Kos Mutiara",
        "alamat": "Jl. Raya Manyaran No. 12, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 850000,
        "jenis": "putri",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "kasur", "lemari", "parkir motor", "air panas"],
        "kamar_kosong": 1,
        "aturan": "Jam malam pukul 23.00.",
        "rating": 4.6,
        "ulasan": 20,
        "whatsapp": "6281234567806",
        "latitude": -7.0540,
        "longitude": 110.4420,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Satpam malam, CCTV.",
            "kebersihan": "🧹 Sangat bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan lebar.",
            "listrik": "⚡ Listrik 2200 watt.",
            "air": "💧 Air PDAM, air panas.",
            "sirkulasi_udara": "🌬️ Kamar AC, nyaman.",
            "pencahayaan": "💡 Sangat terang.",
            "lingkungan": "🌳 Asri."
        }
    },
    {
        "id": 10,
        "nama": "Kos Permata",
        "alamat": "Jl. Bukit Hijau No. 7, Tembalang",
        "kecamatan": "Tembalang",
        "wilayah": "Semarang Selatan",
        "harga": 950000,
        "jenis": "campur",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "kasur", "lemari", "parkir motor", "laundry", "air panas", "tv"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 23.00. Tamu terbatas.",
        "rating": 4.8,
        "ulasan": 28,
        "whatsapp": "6281234567807",
        "latitude": -7.0550,
        "longitude": 110.4430,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Bebas banjir.",
            "keamanan": "🔒 Satpam 24 jam, CCTV.",
            "kebersihan": "🧹 Sangat bersih, petugas.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan mulus.",
            "listrik": "⚡ Listrik 2200 watt, genset.",
            "air": "💧 Air PDAM, air panas.",
            "sirkulasi_udara": "🌬️ Kamar AC.",
            "pencahayaan": "💡 Sangat terang.",
            "lingkungan": "🌳 Lingkungan elite."
        }
    },
    
    # ==================== KECAMATAN BANYUMANIK (5 Kos) ====================
    {
        "id": 11,
        "nama": "Kos Anggrek Banyumanik",
        "alamat": "Jl. Durian Raya No. 3, Banyumanik",
        "kecamatan": "Banyumanik",
        "wilayah": "Semarang Selatan",
        "harga": 700000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "ac", "lemari", "parkir motor", "laundry"],
        "kamar_kosong": 1,
        "aturan": "Jam malam pukul 22.00. Tidak boleh membawa hewan peliharaan.",
        "rating": 4.6,
        "ulasan": 22,
        "whatsapp": "6281234567893",
        "latitude": -7.0670,
        "longitude": 110.4220,
        "dekat": ["kampus", "mall"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Kawasan bebas banjir.",
            "keamanan": "🔒 Keamanan 24 jam dengan satpam, CCTV.",
            "kebersihan": "🧹 Sangat bersih, dibersihkan setiap hari.",
            "kebisingan": "🔊 Lokasi strategis tapi tetap tenang.",
            "akses_jalan": "🚗 Jalan besar, aspal mulus.",
            "listrik": "⚡ Listrik 2200 watt, stabil.",
            "air": "💧 Air PDAM jernih.",
            "sirkulasi_udara": "🌬️ Kamar luas dengan jendela besar.",
            "pencahayaan": "💡 Penerangan sangat terang.",
            "lingkungan": "🏘️ Lingkungan elite, bersih."
        }
    },
    {
        "id": 12,
        "nama": "Kos Sakura Banyumanik",
        "alamat": "Jl. Setiabudi No. 14, Banyumanik",
        "kecamatan": "Banyumanik",
        "wilayah": "Semarang Selatan",
        "harga": 700000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor", "kasur"],
        "kamar_kosong": 1,
        "aturan": "Jam malam pukul 21.00. Tamu lawan jenis tidak diperbolehkan masuk.",
        "rating": 4.2,
        "ulasan": 15,
        "whatsapp": "6281234567894",
        "latitude": -7.0650,
        "longitude": 110.4210,
        "dekat": ["kampus", "rumah sakit"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Ada pos satpam di kompleks.",
            "kebersihan": "🧹 Bersih, dibersihkan rutin.",
            "kebisingan": "🔊 Cukup tenang.",
            "akses_jalan": "🚗 Jalan aspal lebar.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup baik.",
            "pencahayaan": "💡 Penerangan cukup terang.",
            "lingkungan": "🏘️ Lingkungan perumahan."
        }
    },
    {
        "id": 13,
        "nama": "Kos Aster Banyumanik",
        "alamat": "Jl. Binangun No. 9, Banyumanik",
        "kecamatan": "Banyumanik",
        "wilayah": "Semarang Selatan",
        "harga": 550000,
        "jenis": "campur",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor", "dapur"],
        "kamar_kosong": 4,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 3.9,
        "ulasan": 7,
        "whatsapp": "6281234567808",
        "latitude": -7.0680,
        "longitude": 110.4230,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Keamanan standar.",
            "kebersihan": "🧹 Cukup bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan gang, agak sempit.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air sumur.",
            "sirkulasi_udara": "🌬️ Biasa.",
            "pencahayaan": "💡 Cukup.",
            "lingkungan": "🏘️ Padat."
        }
    },
    {
        "id": 14,
        "nama": "Kos Bougenville",
        "alamat": "Jl. Ngesrep Barat No. 25, Banyumanik",
        "kecamatan": "Banyumanik",
        "wilayah": "Semarang Selatan",
        "harga": 800000,
        "jenis": "putri",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "kasur", "lemari", "parkir motor"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 22.30.",
        "rating": 4.4,
        "ulasan": 17,
        "whatsapp": "6281234567809",
        "latitude": -7.0660,
        "longitude": 110.4240,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 CCTV, pagar tinggi.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan bagus.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Kamar AC.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🌳 Nyaman."
        }
    },
    {
        "id": 15,
        "nama": "Kos Melati Banyumanik",
        "alamat": "Jl. Setiabudi Raya No. 30, Banyumanik",
        "kecamatan": "Banyumanik",
        "wilayah": "Semarang Selatan",
        "harga": 750000,
        "jenis": "putra",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor", "kasur", "meja"],
        "kamar_kosong": 3,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.1,
        "ulasan": 13,
        "whatsapp": "6281234567810",
        "latitude": -7.0690,
        "longitude": 110.4250,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Ada satpam.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔊 Agak bising.",
            "akses_jalan": "🚗 Jalan lebar.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🏘️ Ramai."
        }
    },
    
    # ==================== KECAMATAN PEDURUNGAN (3 Kos) ====================
    {
        "id": 16,
        "nama": "Kos Teratai Pedurungan",
        "alamat": "Jl. Pucang Gading No. 7, Pedurungan",
        "kecamatan": "Pedurungan",
        "wilayah": "Semarang Timur",
        "harga": 550000,
        "jenis": "putra",
        "fasilitas": ["kamar mandi luar", "parkir motor", "dapur", "kasur"],
        "kamar_kosong": 4,
        "aturan": "Tidak ada jam malam. Bayar tepat waktu.",
        "rating": 3.9,
        "ulasan": 7,
        "whatsapp": "6281234567895",
        "latitude": -6.9980,
        "longitude": 110.4650,
        "dekat": ["terminal", "pusat kota"],
        "kondisi": {
            "rawan_banjir": True,
            "keterangan_banjir": "⚠️ KAWASAN BANJIR! Sering tergenang.",
            "keamanan": "🔒 Keamanan standar.",
            "kebersihan": "🧹 Cukup bersih.",
            "kebisingan": "🔊 Dekat terminal, cukup bising.",
            "akses_jalan": "🚗 Jalan aspal, sering rusak.",
            "listrik": "⚡ Listrik 900 watt, sering mati.",
            "air": "💧 Air sumur, kadang keruh.",
            "sirkulasi_udara": "🌬️ Kamar sempit.",
            "pencahayaan": "💡 Penerangan minim.",
            "lingkungan": "🏘️ Lingkungan padat."
        }
    },
    {
        "id": 17,
        "nama": "Kos Mawar Pedurungan",
        "alamat": "Jl. Tlogosari No. 12, Pedurungan",
        "kecamatan": "Pedurungan",
        "wilayah": "Semarang Timur",
        "harga": 500000,
        "jenis": "campur",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor", "dapur"],
        "kamar_kosong": 5,
        "aturan": "Tidak ada jam malam.",
        "rating": 3.8,
        "ulasan": 6,
        "whatsapp": "6281234567811",
        "latitude": -6.9990,
        "longitude": 110.4660,
        "dekat": ["terminal"],
        "kondisi": {
            "rawan_banjir": True,
            "keterangan_banjir": "⚠️ Rawan banjir.",
            "keamanan": "🔒 Biasa.",
            "kebersihan": "🧹 Cukup.",
            "kebisingan": "🔊 Bising.",
            "akses_jalan": "🚗 Jalan rusak.",
            "listrik": "⚡ Listrik 900 watt.",
            "air": "💧 Air keruh.",
            "sirkulasi_udara": "🌬️ Pengap.",
            "pencahayaan": "💡 Redup.",
            "lingkungan": "🏘️ Kumuh."
        }
    },
    {
        "id": 18,
        "nama": "Kos Kenanga Pedurungan",
        "alamat": "Jl. Gemah No. 8, Pedurungan",
        "kecamatan": "Pedurungan",
        "wilayah": "Semarang Timur",
        "harga": 600000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 21.00.",
        "rating": 4.0,
        "ulasan": 9,
        "whatsapp": "6281234567812",
        "latitude": -7.0000,
        "longitude": 110.4670,
        "dekat": ["terminal"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Cukup aman.",
            "keamanan": "🔒 Pagar, kunci.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔊 Agak bising.",
            "akses_jalan": "🚗 Jalan aspal.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup.",
            "pencahayaan": "💡 Cukup.",
            "lingkungan": "🏘️ Ramai."
        }
    },
    
    # ==================== KECAMATAN CANDISARI (2 Kos) ====================
    {
        "id": 19,
        "nama": "Kos Nusa Indah Candisari",
        "alamat": "Jl. Candisari No. 3, Candisari",
        "kecamatan": "Candisari",
        "wilayah": "Semarang Selatan",
        "harga": 650000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "kasur", "lemari"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.1,
        "ulasan": 11,
        "whatsapp": "6281234567898",
        "latitude": -7.0280,
        "longitude": 110.4090,
        "dekat": ["rumah sakit", "pusat kota"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Ada satpam di kompleks.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔊 Cukup tenang.",
            "akses_jalan": "🚗 Jalan aspal lebar.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup baik.",
            "pencahayaan": "💡 Penerangan cukup terang.",
            "lingkungan": "🏘️ Lingkungan perumahan."
        }
    },
    {
        "id": 20,
        "nama": "Kos Flamboyan Candisari",
        "alamat": "Jl. Karangrejo No. 15, Candisari",
        "kecamatan": "Candisari",
        "wilayah": "Semarang Selatan",
        "harga": 750000,
        "jenis": "campur",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "parkir motor", "dapur"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.3,
        "ulasan": 14,
        "whatsapp": "6281234567813",
        "latitude": -7.0290,
        "longitude": 110.4080,
        "dekat": ["rumah sakit"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 CCTV.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan bagus.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Kamar AC.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🏘️ Nyaman."
        }
    },
    
    # ==================== KECAMATAN GAJAHMUNGKUR (2 Kos) ====================
    {
        "id": 21,
        "nama": "Kos Gajah Mungkur",
        "alamat": "Jl. Karang Anyar No. 10, Gajahmungkur",
        "kecamatan": "Gajahmungkur",
        "wilayah": "Semarang Selatan",
        "harga": 700000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor", "kasur", "lemari"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.2,
        "ulasan": 12,
        "whatsapp": "6281234567814",
        "latitude": -7.0200,
        "longitude": 110.4100,
        "dekat": ["pusat kota"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Satpam.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔊 Agak bising.",
            "akses_jalan": "🚗 Jalan lebar.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🏘️ Strategis."
        }
    },
    {
        "id": 22,
        "nama": "Kos Mutiara Gajahmungkur",
        "alamat": "Jl. Sampangan No. 5, Gajahmungkur",
        "kecamatan": "Gajahmungkur",
        "wilayah": "Semarang Selatan",
        "harga": 800000,
        "jenis": "putra",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "parkir motor"],
        "kamar_kosong": 1,
        "aturan": "Jam malam pukul 23.00.",
        "rating": 4.4,
        "ulasan": 16,
        "whatsapp": "6281234567815",
        "latitude": -7.0210,
        "longitude": 110.4110,
        "dekat": ["pusat kota"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman.",
            "keamanan": "🔒 CCTV.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan bagus.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Kamar AC.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🏘️ Nyaman."
        }
    },
    
    # ==================== KECAMATAN NGALIYAN (2 Kos) ====================
    {
        "id": 23,
        "nama": "Kos Griya Putra Ngaliyan",
        "alamat": "Jl. Ngaliyan Raya No. 10, Ngaliyan",
        "kecamatan": "Ngaliyan",
        "wilayah": "Semarang Barat",
        "harga": 500000,
        "jenis": "putra",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor", "dapur"],
        "kamar_kosong": 5,
        "aturan": "Tidak ada jam malam. Menjaga kebersihan.",
        "rating": 4.0,
        "ulasan": 8,
        "whatsapp": "6281234567897",
        "latitude": -7.0140,
        "longitude": 110.3590,
        "dekat": ["kampus", "terminal"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Keamanan standar.",
            "kebersihan": "🧹 Cukup bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan aspal, menanjak.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air sumur pegunungan.",
            "sirkulasi_udara": "🌬️ Udara sejuk.",
            "pencahayaan": "💡 Penerangan cukup.",
            "lingkungan": "🌳 Lingkungan asri."
        }
    },
    {
        "id": 24,
        "nama": "Kos Kenanga Ngaliyan",
        "alamat": "Jl. Purwoyoso No. 18, Ngaliyan",
        "kecamatan": "Ngaliyan",
        "wilayah": "Semarang Barat",
        "harga": 600000,
        "jenis": "campur",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor", "dapur"],
        "kamar_kosong": 3,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.1,
        "ulasan": 10,
        "whatsapp": "6281234567816",
        "latitude": -7.0150,
        "longitude": 110.3580,
        "dekat": ["kampus"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman.",
            "keamanan": "🔒 Pagar.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔇 Tenang.",
            "akses_jalan": "🚗 Jalan bagus.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air sumur.",
            "sirkulasi_udara": "🌬️ Cukup.",
            "pencahayaan": "💡 Cukup.",
            "lingkungan": "🌳 Asri."
        }
    },
    
    # ==================== KECAMATAN GENUK (2 Kos) ====================
    {
        "id": 25,
        "nama": "Kos Genuk Asri",
        "alamat": "Jl. Kaligawe Raya No. 17, Genuk",
        "kecamatan": "Genuk",
        "wilayah": "Semarang Timur",
        "harga": 450000,
        "jenis": "campur",
        "fasilitas": ["kamar mandi luar", "parkir motor", "dapur"],
        "kamar_kosong": 6,
        "aturan": "Tidak ada jam malam. Bayar tepat tanggal 1.",
        "rating": 3.7,
        "ulasan": 5,
        "whatsapp": "6281234567899",
        "latitude": -6.9760,
        "longitude": 110.4780,
        "dekat": ["terminal", "pusat kota"],
        "kondisi": {
            "rawan_banjir": True,
            "keterangan_banjir": "⚠️ Rawan banjir rob.",
            "keamanan": "🔒 Keamanan biasa.",
            "kebersihan": "🧹 Cukup bersih.",
            "kebisingan": "🔊 Dekat jalan raya.",
            "akses_jalan": "🚗 Jalan aspal.",
            "listrik": "⚡ Listrik 900 watt.",
            "air": "💧 Air payau.",
            "sirkulasi_udara": "🌬️ Udara panas.",
            "pencahayaan": "💡 Penerangan minim.",
            "lingkungan": "🏘️ Lingkungan padat."
        }
    },
    {
        "id": 26,
        "nama": "Kos Teratai Genuk",
        "alamat": "Jl. Tambakrejo No. 8, Genuk",
        "kecamatan": "Genuk",
        "wilayah": "Semarang Timur",
        "harga": 500000,
        "jenis": "putra",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor"],
        "kamar_kosong": 4,
        "aturan": "Tidak ada jam malam.",
        "rating": 3.8,
        "ulasan": 6,
        "whatsapp": "6281234567817",
        "latitude": -6.9770,
        "longitude": 110.4790,
        "dekat": ["terminal"],
        "kondisi": {
            "rawan_banjir": True,
            "keterangan_banjir": "⚠️ Rawan banjir.",
            "keamanan": "🔒 Biasa.",
            "kebersihan": "🧹 Cukup.",
            "kebisingan": "🔊 Bising.",
            "akses_jalan": "🚗 Jalan rusak.",
            "listrik": "⚡ Listrik 900 watt.",
            "air": "💧 Air payau.",
            "sirkulasi_udara": "🌬️ Pengap.",
            "pencahayaan": "💡 Redup.",
            "lingkungan": "🏘️ Padat."
        }
    },
    
    # ==================== KECAMATAN SEMARANG TENGAH (2 Kos) ====================
    {
        "id": 27,
        "nama": "Kos Cempaka Indah",
        "alamat": "Jl. Gajahmada No. 22, Semarang Tengah",
        "kecamatan": "Semarang Tengah",
        "wilayah": "Semarang Tengah",
        "harga": 1200000,
        "jenis": "campur",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "lemari", "kasur", "meja", "laundry", "parkir motor", "air panas"],
        "kamar_kosong": 2,
        "aturan": "Jam malam pukul 23.00. Tamu diperbolehkan di ruang tamu.",
        "rating": 4.8,
        "ulasan": 30,
        "whatsapp": "6281234567896",
        "latitude": -6.9870,
        "longitude": 110.4200,
        "dekat": ["stasiun", "pusat kota"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman banjir.",
            "keamanan": "🔒 Keamanan sangat baik, satpam 24 jam, CCTV.",
            "kebersihan": "🧹 Sangat bersih.",
            "kebisingan": "🔊 Di pusat kota, cukup bising.",
            "akses_jalan": "🚗 Jalan besar, akses mudah.",
            "listrik": "⚡ Listrik 2200 watt, genset.",
            "air": "💧 Air PDAM, air panas.",
            "sirkulasi_udara": "🌬️ Kamar AC.",
            "pencahayaan": "💡 Penerangan sangat baik.",
            "lingkungan": "🏙️ Lingkungan kota."
        }
    },
    {
        "id": 28,
        "nama": "Kos Mawar Semarang Tengah",
        "alamat": "Jl. Pemuda No. 45, Semarang Tengah",
        "kecamatan": "Semarang Tengah",
        "wilayah": "Semarang Tengah",
        "harga": 1000000,
        "jenis": "putri",
        "fasilitas": ["wifi", "ac", "kamar mandi dalam", "kasur", "lemari", "parkir motor"],
        "kamar_kosong": 3,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.5,
        "ulasan": 20,
        "whatsapp": "6281234567818",
        "latitude": -6.9880,
        "longitude": 110.4210,
        "dekat": ["stasiun", "pusat kota"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman.",
            "keamanan": "🔒 Satpam.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔊 Bising.",
            "akses_jalan": "🚗 Jalan besar.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Kamar AC.",
            "pencahayaan": "💡 Terang.",
            "lingkungan": "🏙️ Pusat kota."
        }
    },
    
    # ==================== KECAMATAN SEMARANG BARAT (1 Kos) ====================
    {
        "id": 29,
        "nama": "Kos Mawar Semarang Barat",
        "alamat": "Jl. Bojong No. 12, Semarang Barat",
        "kecamatan": "Semarang Barat",
        "wilayah": "Semarang Barat",
        "harga": 550000,
        "jenis": "campur",
        "fasilitas": ["wifi", "kamar mandi luar", "parkir motor", "dapur"],
        "kamar_kosong": 4,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 3.9,
        "ulasan": 8,
        "whatsapp": "6281234567819",
        "latitude": -6.9900,
        "longitude": 110.3900,
        "dekat": ["terminal"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman.",
            "keamanan": "🔒 Biasa.",
            "kebersihan": "🧹 Cukup.",
            "kebisingan": "🔊 Agak bising.",
            "akses_jalan": "🚗 Jalan aspal.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup.",
            "pencahayaan": "💡 Cukup.",
            "lingkungan": "🏘️ Ramai."
        }
    },
    
    # ==================== KECAMATAN SEMARANG TIMUR (1 Kos) ====================
    {
        "id": 30,
        "nama": "Kos Mutiara Semarang Timur",
        "alamat": "Jl. Rejomulyo No. 7, Semarang Timur",
        "kecamatan": "Semarang Timur",
        "wilayah": "Semarang Timur",
        "harga": 600000,
        "jenis": "putri",
        "fasilitas": ["wifi", "kamar mandi dalam", "parkir motor", "kasur", "lemari"],
        "kamar_kosong": 3,
        "aturan": "Jam malam pukul 22.00.",
        "rating": 4.0,
        "ulasan": 10,
        "whatsapp": "6281234567820",
        "latitude": -6.9800,
        "longitude": 110.4500,
        "dekat": ["pusat kota"],
        "kondisi": {
            "rawan_banjir": False,
            "keterangan_banjir": "✅ Aman.",
            "keamanan": "🔒 CCTV.",
            "kebersihan": "🧹 Bersih.",
            "kebisingan": "🔊 Agak bising.",
            "akses_jalan": "🚗 Jalan aspal.",
            "listrik": "⚡ Listrik 1300 watt.",
            "air": "💧 Air PDAM.",
            "sirkulasi_udara": "🌬️ Cukup.",
            "pencahayaan": "💡 Cukup.",
            "lingkungan": "🏘️ Ramai."
        }
    },
]


# INTENTS (ditambah reset/clear)
INTENTS = {
    "salam": ["halo", "hai", "hi", "selamat", "pagi", "siang", "malam", "assalamualaikum", "permisi", "kabar", "hello", "hey"],
    "keluar": ["keluar", "selesai", "tutup", "stop", "exit", "bye", "dadah", "sampai jumpa", "selamat tinggal", "quit", "close", "goodbye"],
    "reset": ["reset", "mulai lagi", "clear", "bersihkan", "awal lagi", "start over", "ulang dari awal", "hapus percakapan", "new session", "reset chat", "clear chat"],
    "bantuan": ["bantuan", "bantu", "panduan", "cara", "cara pakai", "help", "tolong", "bingung", "petunjuk", "guide"],
    "kembali_menu": ["menu", "menu utama", "kembali", "home"],
    "terima_kasih": ["terima kasih", "makasih", "thanks", "thank you", "suwun", "trims"],
    
    "cari_kos": ["cari", "kos", "kost", "indekos", "kamar sewa", "cari kos", "temukan", "bantu cari", "mau cari", "nyari kos", "butuh kos", "lagi cari", "sedang mencari", "perlu kos", "tolong carikan"],
    "rekomendasi": ["rekomendasi", "saran", "rekomendasikan", "terbaik", "bagus", "favorit", "pilihan", "yang bagus", "recommend", "top"],
    
    "pilih_lokasi": ["tembalang", "banyumanik", "pedurungan", "candisari", "gajahmungkur", "ngaliyan", "genuk", "semarang barat", "semarang timur", "semarang selatan", "semarang tengah", "semarang utara", "dekat kampus", "dekat stasiun", "dekat terminal", "dekat rumah sakit", "dekat pusat kota", "dekat mall"],
    "pilih_budget": ["budget", "harga", "biaya", "sewa", "murah", "dibawah", "kurang dari", "max", "maksimal", "batas", "rp", "ribu", "juta", "per bulan", "diatas", "lebih dari", "minimal", "range"],
    "pilih_jenis_kos": ["putra", "putri", "campur", "cowok", "cewek", "pria", "wanita", "laki", "perempuan", "mix", "bebas", "gabungan"],
    
    "lihat_detail": ["detail", "rincian", "info lengkap", "informasi", "tentang kos", "jelaskan", "lihat", "info", "deskripsi", "ceritakan", "detail kos"],
    "tanya_fasilitas": ["fasilitas", "fasilitas apa", "ada apa saja", "perlengkapan", "apa saja fasilitas", "disediakan apa", "termasuk apa"],
    "tanya_ketersediaan": ["tersedia", "kosong", "ada kamar", "masih ada", "available", "lowongan", "kamar kosong", "ada yang kosong", "kamar tersedia"],
    "tanya_aturan": ["aturan", "peraturan", "ketentuan", "syarat", "jam malam", "tamu", "boleh", "bolehkah", "larangan", "dilarang"],
    
    "tanya_kondisi_banjir": ["banjir", "rawan banjir", "bebas banjir", "genangan", "sering banjir"],
    "tanya_kondisi_keamanan": ["aman", "keamanan", "satpam", "cctv", "kejahatan", "maling"],
    "tanya_kondisi_kebersihan": ["bersih", "kebersihan", "kotor", "sampah", "dibersihkan"],
    "tanya_kondisi_kebisingan": ["bising", "ramai", "tenang", "sunyi", "sepi", "suara"],
    "tanya_kondisi_akses_jalan": ["akses", "jalan", "mobil", "motor", "aspal", "akses jalan"],
    "tanya_kondisi_listrik": ["listrik", "mati listrik", "padam", "genset", "daya"],
    "tanya_kondisi_air": ["air", "air bersih", "air keruh", "pam", "sumur"],
    "tanya_kondisi_udara": ["udara", "sirkulasi", "pengap", "panas", "dingin", "ventilasi"],
    "tanya_kondisi_pencahayaan": ["lampu", "pencahayaan", "penerangan", "terang", "gelap"],
    "tanya_kondisi_lingkungan": ["lingkungan", "tetangga", "nyaman", "asri", "kumuh"],
    
    "tanya_pemesanan": ["cara pesan", "cara booking", "cara sewa", "prosedur sewa", "bagaimana cara pesan", "langkah pesan", "proses sewa", "registrasi", "daftar", "booking", "pesan sekarang", "pemesanan"],
    "hubungi_pemilik": ["kontak", "wa", "whatsapp", "telepon", "nomor", "hubungi", "call", "telp", "no wa", "owner", "pemilik"],
    
    "minta_lokasi": ["lokasi", "maps", "alamat", "peta", "dimana", "letak", "posisi"],
    "kembali_hasil": ["kembali ke hasil", "hasil sebelumnya", "daftar kos", "tampilkan hasil"],
    
    "fallback": [],
}


# SINONIM
SINONIM = {
    "kost": "kos", "indekos": "kos",
    "cowok": "putra", "pria": "putra", "laki": "putra", "lelaki": "putra",
    "cewek": "putri", "wanita": "putri", "perempuan": "putri",
    "mix": "campur", "bebas": "campur", "gabungan": "campur",
    "rb": "ribu", "k": "ribu", "jt": "juta",
    "gak": "tidak", "nggak": "tidak", "ga": "tidak",
    "deket": "dekat", "sekitar": "dekat",
    "info": "informasi",
    "trus": "lalu", "terus": "lalu",
    "yg": "yang", "yng": "yang",
    "dibawah": "dibawah", "diatas": "diatas",
    "dibwah": "dibawah", "diatas": "diatas",
    "kurang": "kurang", "lebih": "lebih"
}


# LOKASI VALID (16 Kecamatan di Semarang)
LOKASI_VALID = [
    "tembalang", "banyumanik", "pedurungan", "candisari",
    "gajahmungkur", "ngaliyan", "genuk", "semarang barat",
    "semarang timur", "semarang selatan", "semarang tengah", "semarang utara",
    "gayamsari", "gunungpati", "mijen", "tugu"
]

LOKASI_KEDEKATAN = {
    "dekat kampus": "kampus", "kampus": "kampus",
    "dekat undip": "kampus", "undip": "kampus",
    "dekat unnes": "kampus", "unnes": "kampus",
    "dekat stasiun": "stasiun", "stasiun": "stasiun",
    "dekat terminal": "terminal", "terminal": "terminal",
    "dekat rumah sakit": "rumah sakit", "rumah sakit": "rumah sakit",
    "dekat pusat kota": "pusat kota", "pusat kota": "pusat kota",
    "dekat mall": "mall", "mall": "mall",
    "dekat pasar": "pasar", "pasar": "pasar",
    "dekat masjid": "masjid", "masjid": "masjid",
    "dekat gereja": "gereja", "gereja": "gereja"
}

FASILITAS_VALID = [
    "wifi", "ac", "kipas", "kamar mandi dalam", "kamar mandi luar",
    "parkir", "parkir motor", "parkir mobil", "dapur", "lemari",
    "kasur", "meja", "laundry", "air panas", "24 jam", "tv",
    "kulkas", "dispenser", "water heater", "spring bed", "almari",
    "balkon", "taman", "kolam renang", "gym", "rooftop"
]

KONDISI_TYPES = {
    "banjir": ["banjir", "genangan", "air naik"],
    "keamanan": ["aman", "keamanan", "satpam", "cctv"],
    "kebersihan": ["bersih", "kebersihan", "kotor"],
    "kebisingan": ["bising", "ramai", "tenang"],
    "akses_jalan": ["akses", "jalan", "mobil"],
    "listrik": ["listrik", "mati listrik", "padam"],
    "air": ["air", "air bersih", "air keruh"],
    "udara": ["udara", "sirkulasi", "pengap"],
    "pencahayaan": ["lampu", "pencahayaan", "terang"],
    "lingkungan": ["lingkungan", "tetangga", "nyaman"]
}